version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile.dev
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "19006:19006"
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:4000
      - EXPO_PUBLIC_API_URL=http://localhost:4000
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    depends_on:
      - api
    networks:
      - afg-marketplace-dev
    stdin_open: true
    tty: true

  api:
    build:
      context: .
      dockerfile: api/Dockerfile.dev
    volumes:
      - ./api:/api
      - /api/node_modules
    ports:
      - "4000:4000"
      - "9229:9229"  # Node.js debugger port
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/afg_marketplace_dev
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev-jwt-secret-key
      - PORT=4000
      - CORS_ORIGIN=http://localhost:19006
      - DEBUG=*
    depends_on:
      - mongo
      - redis
    networks:
      - afg-marketplace-dev
    stdin_open: true
    tty: true

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_dev_data:/data/db
      - ./scripts/mongo-init-dev.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=afg_marketplace_dev
    networks:
      - afg-marketplace-dev

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes
    networks:
      - afg-marketplace-dev

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    networks:
      - afg-marketplace-dev

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - afg-marketplace-dev

volumes:
  mongo_dev_data:
  redis_dev_data:

networks:
  afg-marketplace-dev:
    driver: bridge